version: '3.8'

services:
  laravel-app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RECOMMENDATION_API_URL: http://fastapi-recommender:8000 # 容器內部調用 FastAPI 的內部端口
      RECOMMENDATION_AB_TEST_SALT: some_random_salt_for_ab_test
      QUEUE_CONNECTION: redis # For async event logging
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      fastapi-recommender:
        condition: service_healthy # 確保 FastAPI 服務健康才啟動
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"] # 基本健康檢查
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  fastapi-recommender:
    build:
      context: ./ai-recommender-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # FastAPI 內部在 8000，外部映射到 8001
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_DB: laravel
    volumes:
      - ./ai-recommender-service:/app
      - ./ai-recommender-service/model:/app/model # 持久化模型目錄
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"] # 檢查健康端點
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "laravel_user", "-plaravel_password"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml # 新增：引入告警規則
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-remote-write-receiver
    depends_on:
      fastapi-recommender:
        condition: service_healthy
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
